apiVersion: v1
kind: Pod
metadata:
  name: simple-api
  labels:
    name: simple-api
spec:
  containers:
  - name: simple-api
    image: uyuy2015/jenkinstest
    ports:
    - containerPort: 3000